### ISSUE TITLE
Utils class fails to create cilent when `PROFILE_NAME` in environment

### ISSUE THREAD

**Issue by jon-peterson** [aws-samples/amazon-bedrock-workshop#17]
If you are using a profile for AWS credentials, `get_bedrock_client` fails with an unexpected keyword error because the boto3 session doesn't accept `profile_name` as a parameter.

Here's a code fragment that exhibits the problem:

```
import os
import sys

module_path = ".."
sys.path.append(os.path.abspath(module_path))
from utils import bedrock

os.environ["AWS_DEFAULT_REGION"] = "us-west-2"
os.environ["AWS_PROFILE"] = "bedrock"

boto3_bedrock = bedrock.get_bedrock_client(
    assumed_role=os.environ.get("BEDROCK_ASSUME_ROLE", None),
    endpoint_url=os.environ.get("BEDROCK_ENDPOINT_URL", None),
    region=os.environ.get("AWS_DEFAULT_REGION", None),
)
```

Running the code gives you this error:

```
Create new client
  Using region: us-west-2
  Using profile: bedrock
Traceback (most recent call last):
  File "/path/to/main.py", line 20, in <module>
    boto3_bedrock = bedrock.get_bedrock_client(
  File "/path/to/utils/bedrock.py", line 75, in get_bedrock_client
    bedrock_client = session.client(
TypeError: Session.client() got an unexpected keyword argument 'profile_name'
```

**Comment by jon-peterson** [comment]
Closing as a duplicate of #16
